- name: Fetch xC Cloud tenant details
  hosts: webservers
  collections:
    - yoctoalex.xc_cloud_modules
  connection: local

  environment:
    XC_API_TOKEN: "your_api_token"
    XC_TENANT: "console.ves.volterra.io"

  tasks:
    - name: fetch current tenant details
      fetch_tenant_settings:
      register: tenant

    - name: print tenant
      debug:
        msg: "{{ tenant }}"